### ISSUE TITLE
Support for Typescript

### ISSUE THREAD

**Issue by jimbuck** [HookyQR/VSCodeJSDocTagComplete#1]
This is an awesome extension! I looked through the source and it seems pretty straightforward. Any chance you can include support for `.ts` files? By support I mean simple completion just like javascript.

If you want to get even fancier, automatically filling in the TS type would be even better (albeit much more complex). But I understand this is much more difficult and may be too complex to easily achieve.

**Comment by HookyQR** [comment]
Hey @JimmyBoh. Basic side done. Didn't look at the TS type auto fill-ins though. New version released.

**Comment by jimbuck** [comment]
Awesome! Thanks @HookyQR!

**Comment by jimbuck** [comment]
Works great!
